spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:novaerp_db}?currentSchema=public
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.novaerp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
